name: CI - test

# CI for our project as a GitHub action
# see https://help.github.com/en/actions/language-and-framework-guides/building-and-testing-java-with-maven

on:
  push:
    branches:
      - '**' # should match all branches
    tags-ignore:
      - '**' # all tags; actually, believe this is default behavior when you specify filter for branches but not tags

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '8.0.242' # The JDK version to make available on the path.
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Clear our artifacts from Maven cache # q: does this work!?!?!
        run: |
          rm -rf ~/.m2/repository/com/engetc/
      - name: Test
        run: |
          mvn post-clean test -T 1C -Dversions.logOutput=false -DprocessDependencies=false -DprocessDependencyManagement=false -Dsurefire.forkCount=2 -Dsurefire.reuseForks=true
